services:
  database:
    extends:
      file: ../default-docker-compose.yml  # Référence au fichier parent
      service: database
    volumes:
      - james_b_united_data_ex_2:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d

volumes:
  james_b_united_data_ex_2:
